wait or keycloak to be healthy

diff --git a/app/inst b/app/inst
--- a/app/inst
+++ b/app/inst
@@ -132,9 +132,18 @@ wait_for_dns () {
 }
 wait_for_dns "$keycloak_server_sso_fqdn" || die
 
+wait_for_keycloak () {
+	local i=0
+	for ((i=0; i<100; i++)); do
+		test "$(docker inspect -f "{{.State.Health.Status}}" "keycloak")" = "healthy" && return 0
+		sleep 2;
+	done
+	echo "ERROR: Container did not come up healthy"
+	return 1
+}
+
 univention-app restart keycloak
-i=0; while [ "$(docker inspect -f "{{.State.Health.Status}}" "keycloak")" != "healthy" ] && [ "$((++i))" -lt 100 ]; do  sleep 2; done; if [ "$i" -eq 100 ]; then echo "ERROR: Container did not come up healthy"; exit 1; fi
-echo "Container is healthy, configuring Keycloak"
+wait_for_keycloak || die
 
 # if init is necessary (ucs realm does not exist),
 # this also sets domain_config_version
@@ -206,8 +215,10 @@ chmod 660 "$keytab_path" || die
 
 univention-keycloak kerberos-config set --server-principal "$servicePrincipal"
 
-# another restart for the cache initialization
-univention-app restart keycloak
+# TODO, test if that is necessary, if not remove
+## another restart for the cache initialization
+#univention-app restart keycloak
+#wait_for_keycloak || die
 
 ucs_addServiceToLocalhost "$app_id" "$@"
 
