feat: configure UMC for SAML login with keycloak on app install
Issue #211

diff --git a/app/inst b/app/inst
--- a/app/inst
+++ b/app/inst
@@ -226,6 +226,25 @@ univention-keycloak kerberos-config set --server-principal "$servicePrincipal"
 
 ucs_addServiceToLocalhost "$app_id" "$@"
 
+configure_umc_keycloak () {
+	univention-keycloak "$@" --binduser "${keycloak_admin_user:-admin}" saml/sp update "https://$hostname.$domainname/univention/saml/metadata" \
+		'{"attributes": {"saml.assertion.lifespan": "'"$umc_saml_assertion_lifetime"'"}}'
+	if is_ucr_true 'umc/web/sso/enabled' && [ -z "$umc_saml_idp_server" ]; then
+		rm /usr/share/univention-management-console/saml/idp/*.xml
+		ucr --debug set umc/saml/idp-server="https://$(univention-keycloak get-keycloak-base-url)/realms/ucs/protocol/saml/descriptor" || return 1
+		[ "$(ls -A /usr/share/univention-management-console/saml/idp/*.xml)" ] || return 1
+
+		service slapd restart
+	fi
+}
+
+if [ "$version_version" == "5.2" ]; then
+	configure_umc_keycloak "$@" || {
+		echo "UMC keycloak configuration failed. Consider attempting manual setup using the Univention Keycloak app manual."
+		ucr unset umc/saml/idp-server
+  }
+fi
+
 joinscript_save_current_version
 
 exit 0
