check for "hostname does not match" ssl error

diff --git a/app/inst b/app/inst
--- a/app/inst
+++ b/app/inst
@@ -142,9 +142,23 @@ wait_for_dns () {
 }
 wait_for_dns "$keycloak_server_sso_fqdn" || die
 
+check_for_ssl_error () {
+	local cert
+	if univention-keycloak --binduser "${keycloak_admin_user:-admin}" realms get 2>&1 | grep -q 'SLCertVerificationError.*hostname.*doesn.t match'; then
+		cert="$(ucr get keycloak/apache2/ssl/certificate)"
+		test -n "$cert" && cert="keycloak/apache2/ssl/certificate=$cert"
+		test -z "$cert" && cert="keycloak/apache2/ssl/certificate not set, using default certficate"
+		echo "ERROR: Broken certificate files configuration!"
+		echo "       There are no valid certificate files for the FQDN of your keycloak server!"
+		echo "         Keycloak fqdn: $keycloak_server_sso_fqdn"
+		echo "         Certficate:    $cert"
+		echo "       See https://docs.software-univention.de/keycloak-app/latest/use-cases.html#external-fqdn-different-from-internal-ucs-name"
+		echo "       for more information."
+	fi
+}
 wait_for_keycloak () {
 	local i=0
-	for ((i=0; i<400; i++)); do
+	for ((i=0; i<300; i++)); do
 		test "$(docker inspect -f "{{.State.Health.Status}}" "keycloak")" = "healthy" && univention-keycloak --binduser "${keycloak_admin_user:-admin}" realms get && return 0
 		sleep 3;
 	done
@@ -152,7 +166,10 @@ wait_for_keycloak () {
 	return 1
 }
 
-wait_for_keycloak || die
+wait_for_keycloak || {
+	check_for_ssl_error
+	die
+}
 univention-app restart keycloak
 wait_for_keycloak || die
 
