Issue #: install only possible in domaincontroller_master

diff --git a/app/preinst.tmpl b/app/preinst.tmpl
--- a/app/preinst.tmpl
+++ b/app/preinst.tmpl
@@ -1,6 +1,39 @@
 #!/bin/bash
 
 set -e
+eval "$(ucr shell)"
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        "--error-file")
+            shift
+            errorfile="$1"
+            shift
+            ;;
+        "--old-version")
+            shift
+            old_version="$1"
+            shift
+            ;;
+        "--version")
+            shift
+            version="$1"
+            shift
+            ;;
+        *)
+            shift
+            ;;
+    esac
+done
+
+if [ "$server_role" != "domaincontroller_master" ]; then
+	keycloak_primary_dn=$(univention-ldapsearch '(&(univentionServerRole=master)(univentionService=keycloak))' 1.1 | grep ^dn)
+	if [ -z "$keycloak_primary_dn" ]; then
+		message="Error: The Keycloak app needs to be installed on the Primary Directory Node first."
+		echo "$message" > "$errorfile"
+		exit 1
+	fi
+fi
 
 # create password
 pwdfile="/etc/keycloak.secret"
